# Generated by Django 4.0.4 on 2022-04-27 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Tipodemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_demanda', models.IntegerField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('detalle', models.TextField()),
                ('rut1', models.IntegerField(blank=True, null=True)),
                ('dv1', models.CharField(blank=True, default='', max_length=2, null=True)),
                ('nombre1', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('apellido1', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('telefono1', models.IntegerField(blank=True, null=True)),
                ('rut2', models.IntegerField(blank=True, null=True)),
                ('dv2', models.CharField(blank=True, default='', max_length=2, null=True)),
                ('nombre2', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('apellido2', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('telefono2', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comuna1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comuna1', to='applegal.comuna')),
                ('comuna2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comuna2', to='applegal.comuna')),
                ('tipodemanda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applegal.tipodemanda')),
            ],
        ),
    ]
